import { Table } from "ts-sql-query/Table";
import { MySqlConnection } from "ts-sql-query/connections/MySqlConnection";

export class DBConnection extends MySqlConnection<'DBConnection'> {
    protected uuidStrategy = 'string' as const
}

export const users = new class users extends Table<DBConnection, 'users'> {
    id = this.autogeneratedPrimaryKey('id', 'string');
    email = this.column('email', 'string');
    username = this.column('username', 'string');
    created_at = this.column('created_at', 'localDateTime')
    passwordHash = this.column('passwordHash', 'string');
    constructor() {
        super('users'); // table name in the database
    }
}
